version: '2'
services:

  build:
    image: klakegg/hugo:ext-alpine
    command: --minify

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    volumes:
      - ./public:/target
      - ./:/src

  server:
    image: klakegg/hugo:ext-alpine
    command: server -DF

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    ports:
      - "1313:1313"

    volumes:
      - ./:/src
